/**
 * Renders a panel displaying an AI-generated description.
 */

import { Box, Card, CardContent, Typography, CircularProgress } from '@mui/material'
import useDescription from './useDescription'
import geminiLogo from '../../../assets/gemini.png'

function DescriptionPanel() {
  const { description, loading } = useDescription()

  const boxStyle = {
    width: '100%',
    height: 'fit-content',
    boxShadow: 1,
    borderRadius: 2,
    fontFamily: 'GoogleSans',
    fontSize: '.95rem',
    textAlign: 'center'
  }

  const geminiWrapperStyle: Object = {
    display: 'flex', 
    flexDirection: 'row', 
    gap: 5,
    fontFamily: 'GoogleSans',
    color: 'darkgrey'
  }

  const headerStyle = {
    fontFamily: 'GoogleSans',
    fontWeight: 'bold',
    paddingBottom: 1,
  }

  return (
    <Box sx={boxStyle}>
      <Card variant='outlined'>
        <CardContent sx={{ justifySelf: 'center', width: '90%' }}>

          <div style={geminiWrapperStyle}>
            <Typography variant='body1'>
              Generated by
            </Typography>
            <img 
              src={geminiLogo}
              alt='Gemini'
              style={{ height: 15 }}
            />
          </div>

          <Typography variant='h6' sx={headerStyle}>
            Description
          </Typography>

          {loading ? <CircularProgress /> : description}

        </CardContent>
      </Card>
    </Box>
  )
}

export default DescriptionPanel