/**
 * Panel displaying an AI-generated description.
 */

import { Box, Card, CardContent, CircularProgress, Typography } from '@mui/material'
import { useAppContext } from '../context.jsx'
import { useState, useEffect } from 'react'
import { fetchAIResponse } from '../api/genai.js'

function AIPanel() {
  const { neoData } = useAppContext()
  const [description, setDescription] = useState("")
  const [loading, setLoading] = useState(false)

  useEffect(() => {
    if (!(Object.keys(neoData)?.length)) return
    async function fetchDescription() {
      try {
        setLoading(true)
        const response = await fetchAIResponse(neoData)
        setDescription(response)
        setLoading(false)
      } catch (error) {
        console.log(error)
      }
    }
    fetchDescription()
  }, [neoData])

  const card = (
    <CardContent sx={{ minHeight: 225, width: 500, justifySelf: 'center' }}>
      <div style={{ display: 'flex', flexDirection: 'row', gap: 5 }}>
        <Typography variant='h8' sx={{
          fontFamily: 'GoogleSans',
          color: 'darkgrey',
        }}>
          Generated by
        </Typography>
        <img 
          src="/assets/gemini.png"
          alt="Gemini"
          style={{ height: 15 }}>
        </img>
      </div>
      <Typography variant='h6' sx={{
        fontFamily: 'GoogleSans',
        fontWeight: 'bold',
        paddingBottom: 1,
        border: 'none'
      }}>
        Description
      </Typography>
      {loading && (
        <CircularProgress></CircularProgress>
      ) || description}
    </CardContent>
  )

  return (
    <Box sx={{
      boxShadow: 1,
      borderRadius: 2,
      fontFamily: 'GoogleSans',
      fontSize: '.95rem',
      textAlign: 'center'
    }}>
      <Card variant="outlined">{card}</Card>
    </Box>
  )
}

export default AIPanel